with-expecter: true
dir: "{{.InterfaceDir}}/../mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: false
issue-845-fix: true
recursive: true
disable-version-string: true

packages:
  github.com/ZanDattSu/pr-reviewer/internal/service:
    config:
      include-regex: ".*Service|TransactionManager"

  github.com/ZanDattSu/pr-reviewer/internal/repository:
    config:
      include-regex: ".*Repository"