// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ZanDattSu/pr-reviewer/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// CheckUserExists provides a mock function with given fields: ctx, userId
func (_m *UserRepository) CheckUserExists(ctx context.Context, userId string) (bool, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_CheckUserExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserExists'
type UserRepository_CheckUserExists_Call struct {
	*mock.Call
}

// CheckUserExists is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *UserRepository_Expecter) CheckUserExists(ctx interface{}, userId interface{}) *UserRepository_CheckUserExists_Call {
	return &UserRepository_CheckUserExists_Call{Call: _e.mock.On("CheckUserExists", ctx, userId)}
}

func (_c *UserRepository_CheckUserExists_Call) Run(run func(ctx context.Context, userId string)) *UserRepository_CheckUserExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_CheckUserExists_Call) Return(_a0 bool, _a1 error) *UserRepository_CheckUserExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_CheckUserExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *UserRepository_CheckUserExists_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateUsersAndReassign provides a mock function with given fields: ctx, userIDs
func (_m *UserRepository) DeactivateUsersAndReassign(ctx context.Context, userIDs []string) (map[string]string, error) {
	ret := _m.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateUsersAndReassign")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]string, error)); ok {
		return rf(ctx, userIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]string); ok {
		r0 = rf(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_DeactivateUsersAndReassign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateUsersAndReassign'
type UserRepository_DeactivateUsersAndReassign_Call struct {
	*mock.Call
}

// DeactivateUsersAndReassign is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []string
func (_e *UserRepository_Expecter) DeactivateUsersAndReassign(ctx interface{}, userIDs interface{}) *UserRepository_DeactivateUsersAndReassign_Call {
	return &UserRepository_DeactivateUsersAndReassign_Call{Call: _e.mock.On("DeactivateUsersAndReassign", ctx, userIDs)}
}

func (_c *UserRepository_DeactivateUsersAndReassign_Call) Run(run func(ctx context.Context, userIDs []string)) *UserRepository_DeactivateUsersAndReassign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *UserRepository_DeactivateUsersAndReassign_Call) Return(_a0 map[string]string, _a1 error) *UserRepository_DeactivateUsersAndReassign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_DeactivateUsersAndReassign_Call) RunAndReturn(run func(context.Context, []string) (map[string]string, error)) *UserRepository_DeactivateUsersAndReassign_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserStats provides a mock function with given fields: ctx, top, onlyActive, onlyOpen
func (_m *UserRepository) GetUserStats(ctx context.Context, top int, onlyActive bool, onlyOpen bool) ([]model.UserStats, error) {
	ret := _m.Called(ctx, top, onlyActive, onlyOpen)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStats")
	}

	var r0 []model.UserStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, bool, bool) ([]model.UserStats, error)); ok {
		return rf(ctx, top, onlyActive, onlyOpen)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, bool, bool) []model.UserStats); ok {
		r0 = rf(ctx, top, onlyActive, onlyOpen)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, bool, bool) error); ok {
		r1 = rf(ctx, top, onlyActive, onlyOpen)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetUserStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserStats'
type UserRepository_GetUserStats_Call struct {
	*mock.Call
}

// GetUserStats is a helper method to define mock.On call
//   - ctx context.Context
//   - top int
//   - onlyActive bool
//   - onlyOpen bool
func (_e *UserRepository_Expecter) GetUserStats(ctx interface{}, top interface{}, onlyActive interface{}, onlyOpen interface{}) *UserRepository_GetUserStats_Call {
	return &UserRepository_GetUserStats_Call{Call: _e.mock.On("GetUserStats", ctx, top, onlyActive, onlyOpen)}
}

func (_c *UserRepository_GetUserStats_Call) Run(run func(ctx context.Context, top int, onlyActive bool, onlyOpen bool)) *UserRepository_GetUserStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(bool), args[3].(bool))
	})
	return _c
}

func (_c *UserRepository_GetUserStats_Call) Return(_a0 []model.UserStats, _a1 error) *UserRepository_GetUserStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetUserStats_Call) RunAndReturn(run func(context.Context, int, bool, bool) ([]model.UserStats, error)) *UserRepository_GetUserStats_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserStatus provides a mock function with given fields: ctx, userID, isActive
func (_m *UserRepository) UpdateUserStatus(ctx context.Context, userID string, isActive bool) (model.User, error) {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStatus")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (model.User, error)); ok {
		return rf(ctx, userID, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) model.User); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_UpdateUserStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserStatus'
type UserRepository_UpdateUserStatus_Call struct {
	*mock.Call
}

// UpdateUserStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - isActive bool
func (_e *UserRepository_Expecter) UpdateUserStatus(ctx interface{}, userID interface{}, isActive interface{}) *UserRepository_UpdateUserStatus_Call {
	return &UserRepository_UpdateUserStatus_Call{Call: _e.mock.On("UpdateUserStatus", ctx, userID, isActive)}
}

func (_c *UserRepository_UpdateUserStatus_Call) Run(run func(ctx context.Context, userID string, isActive bool)) *UserRepository_UpdateUserStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *UserRepository_UpdateUserStatus_Call) Return(_a0 model.User, _a1 error) *UserRepository_UpdateUserStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_UpdateUserStatus_Call) RunAndReturn(run func(context.Context, string, bool) (model.User, error)) *UserRepository_UpdateUserStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UserGetPRReviewer provides a mock function with given fields: ctx, userID
func (_m *UserRepository) UserGetPRReviewer(ctx context.Context, userID string) ([]model.UserAssignedPR, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UserGetPRReviewer")
	}

	var r0 []model.UserAssignedPR
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.UserAssignedPR, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.UserAssignedPR); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserAssignedPR)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_UserGetPRReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserGetPRReviewer'
type UserRepository_UserGetPRReviewer_Call struct {
	*mock.Call
}

// UserGetPRReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRepository_Expecter) UserGetPRReviewer(ctx interface{}, userID interface{}) *UserRepository_UserGetPRReviewer_Call {
	return &UserRepository_UserGetPRReviewer_Call{Call: _e.mock.On("UserGetPRReviewer", ctx, userID)}
}

func (_c *UserRepository_UserGetPRReviewer_Call) Run(run func(ctx context.Context, userID string)) *UserRepository_UserGetPRReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_UserGetPRReviewer_Call) Return(_a0 []model.UserAssignedPR, _a1 error) *UserRepository_UserGetPRReviewer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_UserGetPRReviewer_Call) RunAndReturn(run func(context.Context, string) ([]model.UserAssignedPR, error)) *UserRepository_UserGetPRReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
