// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ReviewerRepository is an autogenerated mock type for the ReviewerRepository type
type ReviewerRepository struct {
	mock.Mock
}

type ReviewerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReviewerRepository) EXPECT() *ReviewerRepository_Expecter {
	return &ReviewerRepository_Expecter{mock: &_m.Mock}
}

// GetReviewersForPR provides a mock function with given fields: ctx, prID
func (_m *ReviewerRepository) GetReviewersForPR(ctx context.Context, prID string) ([]string, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewersForPR")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReviewerRepository_GetReviewersForPR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewersForPR'
type ReviewerRepository_GetReviewersForPR_Call struct {
	*mock.Call
}

// GetReviewersForPR is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *ReviewerRepository_Expecter) GetReviewersForPR(ctx interface{}, prID interface{}) *ReviewerRepository_GetReviewersForPR_Call {
	return &ReviewerRepository_GetReviewersForPR_Call{Call: _e.mock.On("GetReviewersForPR", ctx, prID)}
}

func (_c *ReviewerRepository_GetReviewersForPR_Call) Run(run func(ctx context.Context, prID string)) *ReviewerRepository_GetReviewersForPR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReviewerRepository_GetReviewersForPR_Call) Return(_a0 []string, _a1 error) *ReviewerRepository_GetReviewersForPR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReviewerRepository_GetReviewersForPR_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *ReviewerRepository_GetReviewersForPR_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceReviewer provides a mock function with given fields: ctx, prID, oldReviewerID, newUserID
func (_m *ReviewerRepository) ReplaceReviewer(ctx context.Context, prID string, oldReviewerID string, newUserID string) error {
	ret := _m.Called(ctx, prID, oldReviewerID, newUserID)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, prID, oldReviewerID, newUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReviewerRepository_ReplaceReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceReviewer'
type ReviewerRepository_ReplaceReviewer_Call struct {
	*mock.Call
}

// ReplaceReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - oldReviewerID string
//   - newUserID string
func (_e *ReviewerRepository_Expecter) ReplaceReviewer(ctx interface{}, prID interface{}, oldReviewerID interface{}, newUserID interface{}) *ReviewerRepository_ReplaceReviewer_Call {
	return &ReviewerRepository_ReplaceReviewer_Call{Call: _e.mock.On("ReplaceReviewer", ctx, prID, oldReviewerID, newUserID)}
}

func (_c *ReviewerRepository_ReplaceReviewer_Call) Run(run func(ctx context.Context, prID string, oldReviewerID string, newUserID string)) *ReviewerRepository_ReplaceReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ReviewerRepository_ReplaceReviewer_Call) Return(_a0 error) *ReviewerRepository_ReplaceReviewer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReviewerRepository_ReplaceReviewer_Call) RunAndReturn(run func(context.Context, string, string, string) error) *ReviewerRepository_ReplaceReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// NewReviewerRepository creates a new instance of ReviewerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewerRepository {
	mock := &ReviewerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
