// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ZanDattSu/pr-reviewer/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// TeamRepository is an autogenerated mock type for the TeamRepository type
type TeamRepository struct {
	mock.Mock
}

type TeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamRepository) EXPECT() *TeamRepository_Expecter {
	return &TeamRepository_Expecter{mock: &_m.Mock}
}

// AddTeam provides a mock function with given fields: ctx, _a1
func (_m *TeamRepository) AddTeam(ctx context.Context, _a1 model.Team) (model.Team, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddTeam")
	}

	var r0 model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Team) (model.Team, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Team) model.Team); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.Team)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Team) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_AddTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTeam'
type TeamRepository_AddTeam_Call struct {
	*mock.Call
}

// AddTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 model.Team
func (_e *TeamRepository_Expecter) AddTeam(ctx interface{}, _a1 interface{}) *TeamRepository_AddTeam_Call {
	return &TeamRepository_AddTeam_Call{Call: _e.mock.On("AddTeam", ctx, _a1)}
}

func (_c *TeamRepository_AddTeam_Call) Run(run func(ctx context.Context, _a1 model.Team)) *TeamRepository_AddTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Team))
	})
	return _c
}

func (_c *TeamRepository_AddTeam_Call) Return(_a0 model.Team, _a1 error) *TeamRepository_AddTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_AddTeam_Call) RunAndReturn(run func(context.Context, model.Team) (model.Team, error)) *TeamRepository_AddTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, teamName
func (_m *TeamRepository) GetTeam(ctx context.Context, teamName string) (model.Team, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Team, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Team); ok {
		r0 = rf(ctx, teamName)
	} else {
		r0 = ret.Get(0).(model.Team)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type TeamRepository_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *TeamRepository_Expecter) GetTeam(ctx interface{}, teamName interface{}) *TeamRepository_GetTeam_Call {
	return &TeamRepository_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, teamName)}
}

func (_c *TeamRepository_GetTeam_Call) Run(run func(ctx context.Context, teamName string)) *TeamRepository_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TeamRepository_GetTeam_Call) Return(_a0 model.Team, _a1 error) *TeamRepository_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_GetTeam_Call) RunAndReturn(run func(context.Context, string) (model.Team, error)) *TeamRepository_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamActiveMembersWithoutUser provides a mock function with given fields: ctx, userID
func (_m *TeamRepository) GetTeamActiveMembersWithoutUser(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamActiveMembersWithoutUser")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_GetTeamActiveMembersWithoutUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamActiveMembersWithoutUser'
type TeamRepository_GetTeamActiveMembersWithoutUser_Call struct {
	*mock.Call
}

// GetTeamActiveMembersWithoutUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *TeamRepository_Expecter) GetTeamActiveMembersWithoutUser(ctx interface{}, userID interface{}) *TeamRepository_GetTeamActiveMembersWithoutUser_Call {
	return &TeamRepository_GetTeamActiveMembersWithoutUser_Call{Call: _e.mock.On("GetTeamActiveMembersWithoutUser", ctx, userID)}
}

func (_c *TeamRepository_GetTeamActiveMembersWithoutUser_Call) Run(run func(ctx context.Context, userID string)) *TeamRepository_GetTeamActiveMembersWithoutUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TeamRepository_GetTeamActiveMembersWithoutUser_Call) Return(_a0 []string, _a1 error) *TeamRepository_GetTeamActiveMembersWithoutUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_GetTeamActiveMembersWithoutUser_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *TeamRepository_GetTeamActiveMembersWithoutUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamRepository creates a new instance of TeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamRepository {
	mock := &TeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
