// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ZanDattSu/pr-reviewer/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PullRequestRepository is an autogenerated mock type for the PullRequestRepository type
type PullRequestRepository struct {
	mock.Mock
}

type PullRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PullRequestRepository) EXPECT() *PullRequestRepository_Expecter {
	return &PullRequestRepository_Expecter{mock: &_m.Mock}
}

// CheckPRExists provides a mock function with given fields: ctx, prID
func (_m *PullRequestRepository) CheckPRExists(ctx context.Context, prID string) (bool, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for CheckPRExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestRepository_CheckPRExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPRExists'
type PullRequestRepository_CheckPRExists_Call struct {
	*mock.Call
}

// CheckPRExists is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *PullRequestRepository_Expecter) CheckPRExists(ctx interface{}, prID interface{}) *PullRequestRepository_CheckPRExists_Call {
	return &PullRequestRepository_CheckPRExists_Call{Call: _e.mock.On("CheckPRExists", ctx, prID)}
}

func (_c *PullRequestRepository_CheckPRExists_Call) Run(run func(ctx context.Context, prID string)) *PullRequestRepository_CheckPRExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PullRequestRepository_CheckPRExists_Call) Return(_a0 bool, _a1 error) *PullRequestRepository_CheckPRExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestRepository_CheckPRExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *PullRequestRepository_CheckPRExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRWithReviewers provides a mock function with given fields: ctx, prID
func (_m *PullRequestRepository) GetPRWithReviewers(ctx context.Context, prID string) (model.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPRWithReviewers")
	}

	var r0 model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestRepository_GetPRWithReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRWithReviewers'
type PullRequestRepository_GetPRWithReviewers_Call struct {
	*mock.Call
}

// GetPRWithReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *PullRequestRepository_Expecter) GetPRWithReviewers(ctx interface{}, prID interface{}) *PullRequestRepository_GetPRWithReviewers_Call {
	return &PullRequestRepository_GetPRWithReviewers_Call{Call: _e.mock.On("GetPRWithReviewers", ctx, prID)}
}

func (_c *PullRequestRepository_GetPRWithReviewers_Call) Run(run func(ctx context.Context, prID string)) *PullRequestRepository_GetPRWithReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PullRequestRepository_GetPRWithReviewers_Call) Return(_a0 model.PullRequest, _a1 error) *PullRequestRepository_GetPRWithReviewers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestRepository_GetPRWithReviewers_Call) RunAndReturn(run func(context.Context, string) (model.PullRequest, error)) *PullRequestRepository_GetPRWithReviewers_Call {
	_c.Call.Return(run)
	return _c
}

// InsertPR provides a mock function with given fields: ctx, pr
func (_m *PullRequestRepository) InsertPR(ctx context.Context, pr model.PullRequest) (model.PullRequest, error) {
	ret := _m.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for InsertPR")
	}

	var r0 model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PullRequest) (model.PullRequest, error)); ok {
		return rf(ctx, pr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PullRequest) model.PullRequest); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PullRequest) error); ok {
		r1 = rf(ctx, pr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestRepository_InsertPR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertPR'
type PullRequestRepository_InsertPR_Call struct {
	*mock.Call
}

// InsertPR is a helper method to define mock.On call
//   - ctx context.Context
//   - pr model.PullRequest
func (_e *PullRequestRepository_Expecter) InsertPR(ctx interface{}, pr interface{}) *PullRequestRepository_InsertPR_Call {
	return &PullRequestRepository_InsertPR_Call{Call: _e.mock.On("InsertPR", ctx, pr)}
}

func (_c *PullRequestRepository_InsertPR_Call) Run(run func(ctx context.Context, pr model.PullRequest)) *PullRequestRepository_InsertPR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PullRequest))
	})
	return _c
}

func (_c *PullRequestRepository_InsertPR_Call) Return(_a0 model.PullRequest, _a1 error) *PullRequestRepository_InsertPR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestRepository_InsertPR_Call) RunAndReturn(run func(context.Context, model.PullRequest) (model.PullRequest, error)) *PullRequestRepository_InsertPR_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePRStatus provides a mock function with given fields: ctx, pr, status
func (_m *PullRequestRepository) UpdatePRStatus(ctx context.Context, pr model.PullRequest, status model.Status) (model.PullRequest, error) {
	ret := _m.Called(ctx, pr, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePRStatus")
	}

	var r0 model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PullRequest, model.Status) (model.PullRequest, error)); ok {
		return rf(ctx, pr, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PullRequest, model.Status) model.PullRequest); ok {
		r0 = rf(ctx, pr, status)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PullRequest, model.Status) error); ok {
		r1 = rf(ctx, pr, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestRepository_UpdatePRStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePRStatus'
type PullRequestRepository_UpdatePRStatus_Call struct {
	*mock.Call
}

// UpdatePRStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - pr model.PullRequest
//   - status model.Status
func (_e *PullRequestRepository_Expecter) UpdatePRStatus(ctx interface{}, pr interface{}, status interface{}) *PullRequestRepository_UpdatePRStatus_Call {
	return &PullRequestRepository_UpdatePRStatus_Call{Call: _e.mock.On("UpdatePRStatus", ctx, pr, status)}
}

func (_c *PullRequestRepository_UpdatePRStatus_Call) Run(run func(ctx context.Context, pr model.PullRequest, status model.Status)) *PullRequestRepository_UpdatePRStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PullRequest), args[2].(model.Status))
	})
	return _c
}

func (_c *PullRequestRepository_UpdatePRStatus_Call) Return(_a0 model.PullRequest, _a1 error) *PullRequestRepository_UpdatePRStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestRepository_UpdatePRStatus_Call) RunAndReturn(run func(context.Context, model.PullRequest, model.Status) (model.PullRequest, error)) *PullRequestRepository_UpdatePRStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewPullRequestRepository creates a new instance of PullRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestRepository {
	mock := &PullRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
