// Code generated by ogen, DO NOT EDIT.

package reviewer_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// HealthGet implements GET /health operation.
//
// Проверить работоспособность сервиса.
//
// GET /health
func (UnimplementedHandler) HealthGet(ctx context.Context) (r HealthGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PullRequestCreatePost implements POST /pullRequest/create operation.
//
// Создать PR и автоматически назначить до 2 ревьюверов
// из команды автора.
//
// POST /pullRequest/create
func (UnimplementedHandler) PullRequestCreatePost(ctx context.Context, req *PullRequestCreatePostReq) (r PullRequestCreatePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PullRequestMergePost implements POST /pullRequest/merge operation.
//
// Пометить PR как MERGED (идемпотентная операция).
//
// POST /pullRequest/merge
func (UnimplementedHandler) PullRequestMergePost(ctx context.Context, req *PullRequestMergePostReq) (r PullRequestMergePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PullRequestReassignPost implements POST /pullRequest/reassign operation.
//
// Переназначить конкретного ревьювера на другого из
// его команды.
//
// POST /pullRequest/reassign
func (UnimplementedHandler) PullRequestReassignPost(ctx context.Context, req *PullRequestReassignPostReq) (r PullRequestReassignPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TeamAddPost implements POST /team/add operation.
//
// Создать команду с участниками (создаёт/обновляет
// пользователей).
//
// POST /team/add
func (UnimplementedHandler) TeamAddPost(ctx context.Context, req *Team) (r TeamAddPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TeamGetGet implements GET /team/get operation.
//
// Получить команду с участниками.
//
// GET /team/get
func (UnimplementedHandler) TeamGetGet(ctx context.Context, params TeamGetGetParams) (r TeamGetGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersDeactivatePost implements POST /users/deactivate operation.
//
// Деактивирует переданных пользователей (is_active = false) и
// для всех открытых PR, где они были назначены
// ревьюверами, пытается найти активную замену из их
// команды.
//
// POST /users/deactivate
func (UnimplementedHandler) UsersDeactivatePost(ctx context.Context, req *UsersDeactivatePostReq) (r UsersDeactivatePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersGetReviewGet implements GET /users/getReview operation.
//
// Получить PR'ы, где пользователь назначен ревьювером.
//
// GET /users/getReview
func (UnimplementedHandler) UsersGetReviewGet(ctx context.Context, params UsersGetReviewGetParams) (r UsersGetReviewGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersSetIsActivePost implements POST /users/setIsActive operation.
//
// Установить флаг активности пользователя.
//
// POST /users/setIsActive
func (UnimplementedHandler) UsersSetIsActivePost(ctx context.Context, req *UsersSetIsActivePostReq) (r UsersSetIsActivePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersStatsGet implements GET /users/stats operation.
//
// Возвращает агрегированную статистику по
// пользователям: сколько PR создано каждым
// пользователем. Поддерживаются фильтры: - `top`: вернуть
// только топ-N пользователей - `only_active`: учитывать только
// активных пользователей - `only_open`: учитывать только PR в
// статусе OPEN.
//
// GET /users/stats
func (UnimplementedHandler) UsersStatsGet(ctx context.Context, params UsersStatsGetParams) (r UsersStatsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
