// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ZanDattSu/pr-reviewer/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// DeactivateUsers provides a mock function with given fields: ctx, userIDs
func (_m *UserService) DeactivateUsers(ctx context.Context, userIDs []string) ([]model.DeactivateResult, error) {
	ret := _m.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateUsers")
	}

	var r0 []model.DeactivateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]model.DeactivateResult, error)); ok {
		return rf(ctx, userIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []model.DeactivateResult); ok {
		r0 = rf(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DeactivateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_DeactivateUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateUsers'
type UserService_DeactivateUsers_Call struct {
	*mock.Call
}

// DeactivateUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []string
func (_e *UserService_Expecter) DeactivateUsers(ctx interface{}, userIDs interface{}) *UserService_DeactivateUsers_Call {
	return &UserService_DeactivateUsers_Call{Call: _e.mock.On("DeactivateUsers", ctx, userIDs)}
}

func (_c *UserService_DeactivateUsers_Call) Run(run func(ctx context.Context, userIDs []string)) *UserService_DeactivateUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *UserService_DeactivateUsers_Call) Return(_a0 []model.DeactivateResult, _a1 error) *UserService_DeactivateUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_DeactivateUsers_Call) RunAndReturn(run func(context.Context, []string) ([]model.DeactivateResult, error)) *UserService_DeactivateUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserStats provides a mock function with given fields: ctx, top, onlyActive, onlyOpen
func (_m *UserService) GetUserStats(ctx context.Context, top int, onlyActive bool, onlyOpen bool) ([]model.UserStats, error) {
	ret := _m.Called(ctx, top, onlyActive, onlyOpen)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStats")
	}

	var r0 []model.UserStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, bool, bool) ([]model.UserStats, error)); ok {
		return rf(ctx, top, onlyActive, onlyOpen)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, bool, bool) []model.UserStats); ok {
		r0 = rf(ctx, top, onlyActive, onlyOpen)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, bool, bool) error); ok {
		r1 = rf(ctx, top, onlyActive, onlyOpen)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_GetUserStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserStats'
type UserService_GetUserStats_Call struct {
	*mock.Call
}

// GetUserStats is a helper method to define mock.On call
//   - ctx context.Context
//   - top int
//   - onlyActive bool
//   - onlyOpen bool
func (_e *UserService_Expecter) GetUserStats(ctx interface{}, top interface{}, onlyActive interface{}, onlyOpen interface{}) *UserService_GetUserStats_Call {
	return &UserService_GetUserStats_Call{Call: _e.mock.On("GetUserStats", ctx, top, onlyActive, onlyOpen)}
}

func (_c *UserService_GetUserStats_Call) Run(run func(ctx context.Context, top int, onlyActive bool, onlyOpen bool)) *UserService_GetUserStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(bool), args[3].(bool))
	})
	return _c
}

func (_c *UserService_GetUserStats_Call) Return(_a0 []model.UserStats, _a1 error) *UserService_GetUserStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_GetUserStats_Call) RunAndReturn(run func(context.Context, int, bool, bool) ([]model.UserStats, error)) *UserService_GetUserStats_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserStatus provides a mock function with given fields: ctx, userID, isActive
func (_m *UserService) UpdateUserStatus(ctx context.Context, userID string, isActive bool) (model.User, error) {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStatus")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (model.User, error)); ok {
		return rf(ctx, userID, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) model.User); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_UpdateUserStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserStatus'
type UserService_UpdateUserStatus_Call struct {
	*mock.Call
}

// UpdateUserStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - isActive bool
func (_e *UserService_Expecter) UpdateUserStatus(ctx interface{}, userID interface{}, isActive interface{}) *UserService_UpdateUserStatus_Call {
	return &UserService_UpdateUserStatus_Call{Call: _e.mock.On("UpdateUserStatus", ctx, userID, isActive)}
}

func (_c *UserService_UpdateUserStatus_Call) Run(run func(ctx context.Context, userID string, isActive bool)) *UserService_UpdateUserStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *UserService_UpdateUserStatus_Call) Return(_a0 model.User, _a1 error) *UserService_UpdateUserStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_UpdateUserStatus_Call) RunAndReturn(run func(context.Context, string, bool) (model.User, error)) *UserService_UpdateUserStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UserGetPRReviewer provides a mock function with given fields: ctx, userID
func (_m *UserService) UserGetPRReviewer(ctx context.Context, userID string) ([]model.UserAssignedPR, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UserGetPRReviewer")
	}

	var r0 []model.UserAssignedPR
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.UserAssignedPR, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.UserAssignedPR); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserAssignedPR)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_UserGetPRReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserGetPRReviewer'
type UserService_UserGetPRReviewer_Call struct {
	*mock.Call
}

// UserGetPRReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserService_Expecter) UserGetPRReviewer(ctx interface{}, userID interface{}) *UserService_UserGetPRReviewer_Call {
	return &UserService_UserGetPRReviewer_Call{Call: _e.mock.On("UserGetPRReviewer", ctx, userID)}
}

func (_c *UserService_UserGetPRReviewer_Call) Run(run func(ctx context.Context, userID string)) *UserService_UserGetPRReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_UserGetPRReviewer_Call) Return(_a0 []model.UserAssignedPR, _a1 error) *UserService_UserGetPRReviewer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_UserGetPRReviewer_Call) RunAndReturn(run func(context.Context, string) ([]model.UserAssignedPR, error)) *UserService_UserGetPRReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
