// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ZanDattSu/pr-reviewer/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// TeamService is an autogenerated mock type for the TeamService type
type TeamService struct {
	mock.Mock
}

type TeamService_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamService) EXPECT() *TeamService_Expecter {
	return &TeamService_Expecter{mock: &_m.Mock}
}

// AddTeam provides a mock function with given fields: ctx, _a1
func (_m *TeamService) AddTeam(ctx context.Context, _a1 model.Team) (model.Team, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddTeam")
	}

	var r0 model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Team) (model.Team, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Team) model.Team); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.Team)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Team) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamService_AddTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTeam'
type TeamService_AddTeam_Call struct {
	*mock.Call
}

// AddTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 model.Team
func (_e *TeamService_Expecter) AddTeam(ctx interface{}, _a1 interface{}) *TeamService_AddTeam_Call {
	return &TeamService_AddTeam_Call{Call: _e.mock.On("AddTeam", ctx, _a1)}
}

func (_c *TeamService_AddTeam_Call) Run(run func(ctx context.Context, _a1 model.Team)) *TeamService_AddTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Team))
	})
	return _c
}

func (_c *TeamService_AddTeam_Call) Return(_a0 model.Team, _a1 error) *TeamService_AddTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamService_AddTeam_Call) RunAndReturn(run func(context.Context, model.Team) (model.Team, error)) *TeamService_AddTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, teamName
func (_m *TeamService) GetTeam(ctx context.Context, teamName string) (model.Team, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Team, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Team); ok {
		r0 = rf(ctx, teamName)
	} else {
		r0 = ret.Get(0).(model.Team)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamService_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type TeamService_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *TeamService_Expecter) GetTeam(ctx interface{}, teamName interface{}) *TeamService_GetTeam_Call {
	return &TeamService_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, teamName)}
}

func (_c *TeamService_GetTeam_Call) Run(run func(ctx context.Context, teamName string)) *TeamService_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TeamService_GetTeam_Call) Return(_a0 model.Team, _a1 error) *TeamService_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamService_GetTeam_Call) RunAndReturn(run func(context.Context, string) (model.Team, error)) *TeamService_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamService creates a new instance of TeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamService {
	mock := &TeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
