// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	trm "github.com/avito-tech/go-transaction-manager/trm"
	mock "github.com/stretchr/testify/mock"
)

// TransactionManager is an autogenerated mock type for the TransactionManager type
type TransactionManager struct {
	mock.Mock
}

type TransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionManager) EXPECT() *TransactionManager_Expecter {
	return &TransactionManager_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: ctx, fn
func (_m *TransactionManager) Do(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionManager_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type TransactionManager_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *TransactionManager_Expecter) Do(ctx interface{}, fn interface{}) *TransactionManager_Do_Call {
	return &TransactionManager_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *TransactionManager_Do_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *TransactionManager_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *TransactionManager_Do_Call) Return(_a0 error) *TransactionManager_Do_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionManager_Do_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *TransactionManager_Do_Call {
	_c.Call.Return(run)
	return _c
}

// DoWithSettings provides a mock function with given fields: ctx, s, fn
func (_m *TransactionManager) DoWithSettings(ctx context.Context, s trm.Settings, fn func(context.Context) error) error {
	ret := _m.Called(ctx, s, fn)

	if len(ret) == 0 {
		panic("no return value specified for DoWithSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, trm.Settings, func(context.Context) error) error); ok {
		r0 = rf(ctx, s, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionManager_DoWithSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWithSettings'
type TransactionManager_DoWithSettings_Call struct {
	*mock.Call
}

// DoWithSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - s trm.Settings
//   - fn func(context.Context) error
func (_e *TransactionManager_Expecter) DoWithSettings(ctx interface{}, s interface{}, fn interface{}) *TransactionManager_DoWithSettings_Call {
	return &TransactionManager_DoWithSettings_Call{Call: _e.mock.On("DoWithSettings", ctx, s, fn)}
}

func (_c *TransactionManager_DoWithSettings_Call) Run(run func(ctx context.Context, s trm.Settings, fn func(context.Context) error)) *TransactionManager_DoWithSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(trm.Settings), args[2].(func(context.Context) error))
	})
	return _c
}

func (_c *TransactionManager_DoWithSettings_Call) Return(_a0 error) *TransactionManager_DoWithSettings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionManager_DoWithSettings_Call) RunAndReturn(run func(context.Context, trm.Settings, func(context.Context) error) error) *TransactionManager_DoWithSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionManager creates a new instance of TransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionManager {
	mock := &TransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
