// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ZanDattSu/pr-reviewer/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PRService is an autogenerated mock type for the PRService type
type PRService struct {
	mock.Mock
}

type PRService_Expecter struct {
	mock *mock.Mock
}

func (_m *PRService) EXPECT() *PRService_Expecter {
	return &PRService_Expecter{mock: &_m.Mock}
}

// CreatePullRequest provides a mock function with given fields: ctx, pullRequestID, pullRequestName, authorID
func (_m *PRService) CreatePullRequest(ctx context.Context, pullRequestID string, pullRequestName string, authorID string) (model.PullRequest, error) {
	ret := _m.Called(ctx, pullRequestID, pullRequestName, authorID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (model.PullRequest, error)); ok {
		return rf(ctx, pullRequestID, pullRequestName, authorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) model.PullRequest); ok {
		r0 = rf(ctx, pullRequestID, pullRequestName, authorID)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, pullRequestID, pullRequestName, authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PRService_CreatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequest'
type PRService_CreatePullRequest_Call struct {
	*mock.Call
}

// CreatePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - pullRequestID string
//   - pullRequestName string
//   - authorID string
func (_e *PRService_Expecter) CreatePullRequest(ctx interface{}, pullRequestID interface{}, pullRequestName interface{}, authorID interface{}) *PRService_CreatePullRequest_Call {
	return &PRService_CreatePullRequest_Call{Call: _e.mock.On("CreatePullRequest", ctx, pullRequestID, pullRequestName, authorID)}
}

func (_c *PRService_CreatePullRequest_Call) Run(run func(ctx context.Context, pullRequestID string, pullRequestName string, authorID string)) *PRService_CreatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *PRService_CreatePullRequest_Call) Return(_a0 model.PullRequest, _a1 error) *PRService_CreatePullRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PRService_CreatePullRequest_Call) RunAndReturn(run func(context.Context, string, string, string) (model.PullRequest, error)) *PRService_CreatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// MergePullRequest provides a mock function with given fields: ctx, pullRequestID
func (_m *PRService) MergePullRequest(ctx context.Context, pullRequestID string) (model.PullRequest, error) {
	ret := _m.Called(ctx, pullRequestID)

	if len(ret) == 0 {
		panic("no return value specified for MergePullRequest")
	}

	var r0 model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.PullRequest, error)); ok {
		return rf(ctx, pullRequestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.PullRequest); ok {
		r0 = rf(ctx, pullRequestID)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pullRequestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PRService_MergePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePullRequest'
type PRService_MergePullRequest_Call struct {
	*mock.Call
}

// MergePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - pullRequestID string
func (_e *PRService_Expecter) MergePullRequest(ctx interface{}, pullRequestID interface{}) *PRService_MergePullRequest_Call {
	return &PRService_MergePullRequest_Call{Call: _e.mock.On("MergePullRequest", ctx, pullRequestID)}
}

func (_c *PRService_MergePullRequest_Call) Run(run func(ctx context.Context, pullRequestID string)) *PRService_MergePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PRService_MergePullRequest_Call) Return(_a0 model.PullRequest, _a1 error) *PRService_MergePullRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PRService_MergePullRequest_Call) RunAndReturn(run func(context.Context, string) (model.PullRequest, error)) *PRService_MergePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignPullRequest provides a mock function with given fields: ctx, pullRequestID, oldReviewerID
func (_m *PRService) ReassignPullRequest(ctx context.Context, pullRequestID string, oldReviewerID string) (model.PullRequest, string, error) {
	ret := _m.Called(ctx, pullRequestID, oldReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignPullRequest")
	}

	var r0 model.PullRequest
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.PullRequest, string, error)); ok {
		return rf(ctx, pullRequestID, oldReviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.PullRequest); ok {
		r0 = rf(ctx, pullRequestID, oldReviewerID)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, pullRequestID, oldReviewerID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, pullRequestID, oldReviewerID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PRService_ReassignPullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignPullRequest'
type PRService_ReassignPullRequest_Call struct {
	*mock.Call
}

// ReassignPullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - pullRequestID string
//   - oldReviewerID string
func (_e *PRService_Expecter) ReassignPullRequest(ctx interface{}, pullRequestID interface{}, oldReviewerID interface{}) *PRService_ReassignPullRequest_Call {
	return &PRService_ReassignPullRequest_Call{Call: _e.mock.On("ReassignPullRequest", ctx, pullRequestID, oldReviewerID)}
}

func (_c *PRService_ReassignPullRequest_Call) Run(run func(ctx context.Context, pullRequestID string, oldReviewerID string)) *PRService_ReassignPullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *PRService_ReassignPullRequest_Call) Return(_a0 model.PullRequest, _a1 string, _a2 error) *PRService_ReassignPullRequest_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *PRService_ReassignPullRequest_Call) RunAndReturn(run func(context.Context, string, string) (model.PullRequest, string, error)) *PRService_ReassignPullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewPRService creates a new instance of PRService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRService {
	mock := &PRService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
