// Code generated by ogen, DO NOT EDIT.

package reviewer_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	HealthGetOperation               OperationName = "HealthGet"
	PullRequestCreatePostOperation   OperationName = "PullRequestCreatePost"
	PullRequestMergePostOperation    OperationName = "PullRequestMergePost"
	PullRequestReassignPostOperation OperationName = "PullRequestReassignPost"
	TeamAddPostOperation             OperationName = "TeamAddPost"
	TeamGetGetOperation              OperationName = "TeamGetGet"
	UsersGetReviewGetOperation       OperationName = "UsersGetReviewGet"
	UsersSetIsActivePostOperation    OperationName = "UsersSetIsActivePost"
)
