// Code generated by ogen, DO NOT EDIT.
package reviewer_v1

type PullRequestCreatePostRes interface {
	pullRequestCreatePostRes()
}

type PullRequestMergePostRes interface {
	pullRequestMergePostRes()
}

type PullRequestReassignPostRes interface {
	pullRequestReassignPostRes()
}

type TeamAddPostRes interface {
	teamAddPostRes()
}

type TeamGetGetRes interface {
	teamGetGetRes()
}

type UsersSetIsActivePostRes interface {
	usersSetIsActivePostRes()
}
